# Generated by Django 3.2.3 on 2021-12-15 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import services.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TaiyoInfo', '0002_alter_addres_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_or_sell', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4)),
                ('basic_price', models.FloatField()),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='')),
                ('excel_file_link', models.URLField(blank=True, max_length=300, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='')),
                ('pdf_file_link', models.URLField(blank=True, max_length=300, null=True)),
                ('image_1', models.FileField(blank=True, null=True, upload_to='')),
                ('image_1_link', models.URLField(blank=True, max_length=300, null=True)),
                ('image_2', models.FileField(blank=True, null=True, upload_to='')),
                ('image_2_link', models.URLField(blank=True, max_length=300, null=True)),
                ('image_3', models.FileField(blank=True, null=True, upload_to='')),
                ('image_3_link', models.URLField(blank=True, max_length=300, null=True)),
                ('image_4', models.FileField(blank=True, null=True, upload_to='')),
                ('image_4_link', models.URLField(blank=True, max_length=300, null=True)),
                ('quality', models.CharField(choices=[('Prime', 'Prime'), ('Defective', 'Defective')], max_length=10)),
                ('thickness', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('grade_or_spec', models.CharField(max_length=50)),
                ('temper', models.CharField(choices=[('Hard', 'Hard'), ('Soft', 'Soft')], max_length=4)),
                ('specification_number', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('coating_in_gsm', models.CharField(max_length=30)),
                ('product_description', models.TextField()),
                ('bidding', models.BooleanField()),
                ('bidding_close_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author_name', models.CharField(max_length=40)),
                ('author_mobile_number', models.CharField(max_length=10, validators=[services.validators.validate_phone_number])),
                ('author_country', models.CharField(max_length=20)),
                ('author_business_address', models.CharField(max_length=100)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaiyoInfo.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('selected', models.BooleanField(default=False)),
                ('advertisement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ads.advertisement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
