# Generated by Django 3.2.3 on 2021-12-08 05:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_or_sell', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4)),
                ('basic_price', models.FloatField()),
                ('excel_file', models.URLField(blank=True, max_length=300, null=True)),
                ('pdf_file', models.URLField(blank=True, max_length=300, null=True)),
                ('image_1', models.URLField(blank=True, max_length=300, null=True)),
                ('image_2', models.URLField(blank=True, max_length=300, null=True)),
                ('image_3', models.URLField(blank=True, max_length=300, null=True)),
                ('image_4', models.URLField(blank=True, max_length=300, null=True)),
                ('quality', models.CharField(choices=[('Prime', 'Prime'), ('Defective', 'Defective')], max_length=10)),
                ('thickness', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('grade_or_spec', models.CharField(max_length=50)),
                ('temper', models.CharField(choices=[('Hard', 'Hard'), ('Soft', 'Soft')], max_length=4)),
                ('specification_number', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('coating_in_gsm', models.CharField(max_length=30)),
                ('product_description', models.TextField()),
                ('bidding', models.BooleanField()),
                ('bidding_close_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author_name', models.CharField(max_length=40)),
                ('author_mobile_name', models.CharField(max_length=10)),
                ('author_contry', models.CharField(max_length=20)),
                ('author_buisness_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('selected', models.BooleanField(default=False)),
                ('advertisement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ads.advertisement')),
            ],
        ),
    ]
