# Generated by Django 3.2.3 on 2021-12-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='bidding',
            field=models.BooleanField(default=True),
        ),
    ]
