# Generated by Django 3.2.3 on 2021-12-04 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TaiyoInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaiyoInfo.product'),
        ),
        migrations.AddField(
            model_name='adimages',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ads.advertisement'),
        ),
    ]
