# Generated by Django 3.2.3 on 2021-12-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='author_buisness_address',
            new_name='author_business_address',
        ),
    ]
