# Generated by Django 3.2.3 on 2022-01-14 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='author_business_address',
            new_name='business_address',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='author_mobile_number',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='author_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='author_country',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='city',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='country',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='state',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 18, 53, 42, 831814, tzinfo=utc)),
        ),
    ]
