# Generated by Django 3.2.3 on 2021-12-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='author_contry',
            new_name='author_country',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='author_mobile_name',
            new_name='author_mobile_number',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image_1_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image_2_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image_3_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='image_4_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
