# Generated by Django 3.2.3 on 2021-12-29 07:59

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0002_alter_advertisement_bidding_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='basic_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 7, 59, 34, 40198, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.FloatField(),
        ),
    ]
