# Generated by Django 3.2.3 on 2022-01-15 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='city',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='country',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='state',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 19, 2, 45, 717282, tzinfo=utc)),
        ),
    ]
