# Generated by Django 3.2.3 on 2021-12-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0002_rename_author_buisness_address_advertisement_author_business_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='thickness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='width',
            field=models.FloatField(),
        ),
    ]
