# Generated by Django 3.2.3 on 2021-12-27 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 19, 4, 50, 195084, tzinfo=utc)),
        ),
    ]
