# Generated by Django 3.2.3 on 2022-01-08 07:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 7, 33, 19, 524013, tzinfo=utc)),
        ),
    ]
