# Generated by Django 3.2.3 on 2022-01-16 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 5, 35, 18, 113659, tzinfo=utc)),
        ),
    ]
