# Generated by Django 3.2.3 on 2021-12-03 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0003_auto_20211203_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='bids',
        ),
        migrations.AddField(
            model_name='bid',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ads.advertisement'),
        ),
    ]
