# Generated by Django 3.2.3 on 2022-01-14 17:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        ('Ads', '0003_alter_advertisement_bidding_close_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='latitude',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='longitude',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 17, 20, 50, 173407, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='features.product'),
        ),
    ]
