# Generated by Django 3.2.3 on 2022-01-14 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0004_auto_20220114_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='grade_or_spec',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='length',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='thickness',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='width',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='dimentions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 17, 30, 56, 510626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='coating_in_gsm',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='quality',
            field=models.CharField(blank=True, choices=[('Prime', 'Prime'), ('Defective', 'Defective')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='specification_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='temper',
            field=models.CharField(blank=True, choices=[('Hard', 'Hard'), ('Soft', 'Soft')], max_length=4, null=True),
        ),
    ]
