# Generated by Django 3.2.3 on 2022-01-16 04:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0004_auto_20220116_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='approval',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 4, 37, 49, 616318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='latitude',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='longitude',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='visible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
