# Generated by Django 3.2.3 on 2021-12-03 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0004_auto_20211203_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='image',
            new_name='excel_file',
        ),
        migrations.AddField(
            model_name='bid',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, max_length=300, null=True)),
                ('advertisement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ads.advertisement')),
            ],
        ),
    ]
