# Generated by Django 3.2.3 on 2022-01-16 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0005_alter_advertisement_bidding_close_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 18, 51, 0, 368555, tzinfo=utc)),
        ),
    ]
