# Generated by Django 3.2.3 on 2022-01-14 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0005_auto_20220114_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 17, 33, 2, 357571, tzinfo=utc)),
        ),
    ]
