# Generated by Django 3.2.3 on 2022-01-16 19:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0006_auto_20220117_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 19, 7, 19, 533811, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='latitude',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='longitude',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
