# Generated by Django 3.2.3 on 2022-01-16 19:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0007_auto_20220117_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 19, 16, 44, 661041, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_1',
            field=models.FileField(default='/static/image/notfound.jpg', upload_to=''),
        ),
    ]
