# Generated by Django 3.2.3 on 2022-03-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0016_alter_advertisement_bidding_close_date'),
        ('Ads', '0016_auto_20220126_2336'),
    ]

    operations = [
    ]
