# Generated by Django 3.2.3 on 2022-03-20 17:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0017_merge_20220320_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 17, 16, 8, 253209, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='temper',
            field=models.CharField(blank=True, choices=[('Hard', 'Hard'), ('Soft', 'Soft'), ('Any', 'Any')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 17, 16, 8, 253347, tzinfo=utc)),
        ),
    ]
