# Generated by Django 3.2.3 on 2023-05-15 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0018_auto_20220320_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 9, 8, 42, 152542, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 9, 8, 42, 152678, tzinfo=utc)),
        ),
    ]
