# Generated by Django 3.2.3 on 2024-02-20 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0020_auto_20230515_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 7, 10, 31, 883378, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 7, 10, 31, 883519, tzinfo=utc)),
        ),
    ]
