# Generated by Django 3.2.3 on 2024-02-20 08:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0021_auto_20240220_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='bidding_close_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 8, 2, 59, 740100, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 8, 2, 59, 740236, tzinfo=utc)),
        ),
    ]
