# Generated by Django 3.2.3 on 2022-01-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.BooleanField(default=False)),
                ('temper', models.BooleanField(default=False)),
                ('dimensions', models.BooleanField(default=False)),
                ('grade', models.BooleanField(default=False)),
                ('specification_number', models.BooleanField(default=False)),
                ('quantity', models.BooleanField(default=False)),
                ('coating_in_gsm', models.BooleanField(default=False)),
                ('product_description', models.BooleanField(default=False)),
                ('color', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.product')),
            ],
            options={
                'verbose_name': 'Product Field',
            },
        ),
    ]
