# Generated by Django 3.2.3 on 2022-01-26 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Sub Categorie',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='coating_in_gsm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='temper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductFields',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='features.subcategory'),
        ),
    ]
