# Generated by Django 3.2.3 on 2022-01-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_remove_productfields_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coating_in_gsm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='specification_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='temper',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductFields',
        ),
    ]
