# Generated by Django 3.2.3 on 2022-01-08 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0003_alter_advertisement_bidding_close_date'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='advertisement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Ads.advertisement'),
            preserve_default=False,
        ),
    ]
