# Generated by Django 3.2.3 on 2021-12-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='destroy_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
