# Generated by Django 3.2.3 on 2022-01-08 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0004_alter_advertisement_bidding_close_date'),
        ('user', '0002_notification_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ads.advertisement'),
        ),
    ]
