# Generated by Django 3.2.3 on 2021-12-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/taiyo-768b4.appspot.com/o/Users%2Fdefault.png?alt=media&token=4fdd5a7a-cb6c-41c5-bcfc-5b95352a64bf', max_length=255, null=True),
        ),
    ]
