# Generated by Django 3.2.3 on 2021-12-20 20:35

from django.db import migrations, models
import services.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gst_number',
            field=models.CharField(max_length=15, validators=[services.validators.validate_gst_number]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[services.validators.validate_phone_number]),
        ),
    ]
