# Generated by Django 3.2.3 on 2021-12-02 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211201_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='package_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
