# Generated by Django 3.1.4 on 2021-11-26 19:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('generation_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_condition', ckeditor.fields.RichTextField()),
                ('privacy_policies', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='GenralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.URLField()),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('intro', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('email', models.EmailField(default='', max_length=50)),
                ('contact', models.CharField(default='', max_length=10)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linked_in', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('android_store', models.URLField(blank=True, null=True)),
                ('apple_store', models.URLField(blank=True, null=True)),
                ('copyright', models.CharField(max_length=4)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TaiyoInfo.addres')),
                ('policies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TaiyoInfo.policy')),
            ],
        ),
    ]
