# Generated by Django 3.2.3 on 2021-12-10 07:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import services.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6, validators=[services.validators.validate_pincode])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, validators=[services.validators.validate_email_id])),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.FileField(null=True, upload_to='')),
                ('icon_link', models.URLField(blank=True, max_length=300, null=True)),
                ('cover_image', models.FileField(null=True, upload_to='')),
                ('cover_image_link', models.URLField(blank=True, null=True)),
                ('intro', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=50, null=True, validators=[services.validators.validate_email_id])),
                ('phone_number', models.CharField(max_length=10, null=True, validators=[services.validators.validate_phone_number])),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linked_in', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('android_store', models.URLField(blank=True, null=True)),
                ('apple_store', models.URLField(blank=True, null=True)),
                ('copyright', models.CharField(max_length=4, validators=[services.validators.validate_copyright])),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, validators=[services.validators.validate_email_id])),
                ('generation_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_condition', ckeditor.fields.RichTextField()),
                ('privacy_policies', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('days', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaiyoInfo.category')),
            ],
        ),
    ]
