# Generated by Django 3.2.3 on 2022-03-20 17:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaiyoInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
