# Generated by Django 3.2.3 on 2021-12-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaiyoInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addres',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
