# Generated by Django 3.2.3 on 2022-01-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0004_auto_20220114_2250'),
        ('TaiyoInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
