# Generated by Django 3.2.3 on 2021-12-06 05:00

from django.db import migrations, models
import services.validators


class Migration(migrations.Migration):

    dependencies = [
        ('TaiyoInfo', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, validators=[services.validators.validate_email_id])),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
