# Generated by Django 3.2.3 on 2021-11-27 08:23

from django.db import migrations, models
import django.db.models.deletion
import services.validators


class Migration(migrations.Migration):

    dependencies = [
        ('TaiyoInfo', '0002_auto_20211127_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.URLField()),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('intro', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=50, null=True, validators=[services.validators.validate_email_id])),
                ('contact', models.CharField(max_length=10, null=True, validators=[services.validators.validate_phone_number])),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linked_in', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('android_store', models.URLField(blank=True, null=True)),
                ('apple_store', models.URLField(blank=True, null=True)),
                ('copyright', models.CharField(max_length=4, validators=[services.validators.validate_copyright])),
            ],
        ),
        migrations.AlterField(
            model_name='addres',
            name='pincode',
            field=models.CharField(max_length=6, validators=[services.validators.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=50, validators=[services.validators.validate_email_id]),
        ),
        migrations.DeleteModel(
            name='GenralInfo',
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TaiyoInfo.addres'),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='policies',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TaiyoInfo.policy'),
        ),
    ]
